


INSERT INTO ROLE VALUES(1,'USER_BASIC')
INSERT INTO ROLE VALUES(2,'USER_PREMIUM')
INSERT INTO ROLE VALUES(3,'COMPANY_BASIC')
INSERT INTO ROLE VALUES(4,'COMPANY_PREMIUM')
INSERT INTO ROLE VALUES(5,'ADMIN')

--INSERT INTO USER VALUES (1,'04064842529',TRUE,'DMJESUS89@GMAIL.COM','$2a$10$STfPiUWygjXPFWjW7jdLJe/S6R6l.vcLc5YAZuNCZSgSZGLEU7ITu','DMJESUS89')
--INSERT INTO ADDRESS VALUES (1,'RUA DOUTOR PLINICIO', 1)

--INSERT INTO USER_ROLE VALUES(1,1,1)
